kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
data:
  NODE_ENV: 'staging'
  PORT: '3000'
  DB_NAME: 'neondb'
  DB_USER: 'neondb_owner'
  DB_PASSWORD: 'npg_ckbSC0MDrn5z'
  DB_HOST: 'ep-purple-field-abstdy8v.eu-west-2.aws.neon.tech'
  DB_SSL_REQUIRE: 'true'
  URL_COREAPI: 'https://uat-bbcoreapi.microcred.net'
  AUTH_LOG_COREAPI: 'MatriXirtaM'
  AUTH_PWD_COREAPI: 'Z1ON0101'