apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 8500
    protocol: TCP
    name: registry
  selector:
    app: {{ .Values.appName }}
    tier: backend
  type: NodePort
